server:
  port: 8070
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ecommerce_order_cataloge
    username: firas
    password: Firas123@
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:tn.firas.orderservice.kafka.OrderConfirmation


application:
  config:
    customer-url: http://localhost:8222/api/customers
    product-url: http://localhost:8222/api/products
