server:
  port: 8050
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce_product_catalog
    username: firas
    password: Firas123@
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
file:
  upload-dir: ./uploads

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
