server:
  port: 8090
spring:
  data:
    mongodb:
      username: firas
      password: firas
      host: localhost
      port: 27017
      database: user_db
      authentication-database: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: firashkimi97@gmail.com
    password: zcflfcdfnsjewtcq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
